#!/bin/bash

# create directory structure
mkdir .................

# create empty files
touch .................

# add lines to README.md
echo ..................
echo ..................
echo ..................
echo ..................
